### ISSUE TITLE
CodeInspectBoxSummarize[File["path"]] causes errors

### ISSUE THREAD

**Issue by JonMcLoone** [WolframResearch/codeinspector#1]
Since there is no usage message for CodeInspectBoxSummarize is it meant to be a public symbol?

Because it is on the context path, it shows on autocompletion for CodeInspectSummarize which is what I intended to enter when I entered...

```
CodeInspectBoxSummarize[File["path"]]  
```

resulting in errors:

```
Do::iterb: Iterator {CodeInspector`Boxes`Private`lint,CodeInspector`Boxes`Private`lints$185609} does not have appropriate bounds.

Join::heads: Heads List and CodeParser`CodeConcreteParseBox at positions 1 and 2 are expected to be the same.
```

**Comment by bostick** [comment]
This should behave better with changes I just pushed to CodeParser and CodeInspector

<img width="717" alt="image" src="https://user-images.githubusercontent.com/183619/79468913-28527980-7fc5-11ea-9f8c-ad7f61f53d76.png">

**Comment by szhorvat** [comment]
Ah, so that one parses boxes. I never knew what it does, but it comes up first in the auto-completion, so I accidentally entered it instead of `CodeInspectSummarize` several times.
