### ISSUE TITLE
Publish 1.2 to paclet server 

### ISSUE THREAD

**Issue by kenkangxgwe** [WolframResearch/codeinspector#10]
The current version (1.2) seems only available on MMA 12.3. Do we have the plan to upload it to the official paclet server for earlier versions?

**Comment by bostick** [comment]
CodeParser 1.2, CodeInspector 1.2, and CodeFormatter 1.2 should all be live on the paclet server now.

**Comment by kenkangxgwe** [comment]
Great, thanks!
