### ISSUE TITLE
Error Get::noopen: Cannot open CodeFormatter`.

### ISSUE THREAD

**Issue by Marten-Reehorst** [WolframResearch/codeinspector#11]
I think the line `PacletInstall["CodeFormatter"]` should be added to the installation instructions for versions below 12.2 (I have 12.1 myself), where it says to install with `PacletInstall["CodeParser"]
PacletInstall["CodeInspector"]`. Otherwise I get the error `Error Get::noopen: Cannot open CodeFormatter`.`

**Comment by bostick** [comment]
Good idea, I updated the instructions (I'm not going to draw a distinction between 12.2+ or not, I make a stronger dependency in the future). Thanks!
