### ISSUE TITLE
CodeInspect does not know about ApplyTo sugar

### ISSUE THREAD

**Issue by martinky24** [WolframResearch/codeinspector#6]
[`ApplyTo`](https://reference.wolfram.com/language/ref/ApplyTo.html) is new in 12.2. `CodeInspect` (and co) flags it as problematic:
```
In[1]:= Needs["CodeInspector`"]

In[2]:= CodeInspect["f=1;f//=Sin"]

Out[2]= {
CodeInspector`InspectionObject[
 "ExpectedOperand", "Expected an operand.", "Fatal", 
Association[
  CodeParser`Source -> {{1, 8}, {1, 8}}, ConfidenceLevel -> 1.]]}
```

Environment info:
```
In[3]:= $Version
Out[3]= "12.2.0 for Mac OS X x86 (64-bit) (December 3, 2020)"

In[4]:= PacletObject["CodeInspector"]["Version"]
Out[4]= "1.1.1"
```

**Comment by martinky24** [comment]
Looking at this closer, I'd imagine the issue actually lies in CodeParse:

```
CodeParse["f=1;f//=Sin"]
```
contains an ErrorNode.

**Comment by bostick** [comment]
The version of CodeParser on the paclet server has not yet been updated.

Building CodeParser from sources on GitHub should allow `//=` to be parsed.

**Comment by bostick** [comment]
I think this is obviated with the CodeTools 1.2 paclet update that is now on the paclet server
